name: Bhubaneswar Gold Price Tracker

on:
  schedule:
    # Every 4 hours
    - cron: "0 */4 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  gold-tracker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
           node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install chromium

      - name: Run Gold Tracker
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node index.js

      # Upload debug files even if scraper fails
      - name: Upload Debug Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            page.html
            page.png
          if-no-files-found: ignore

      # Save updated price.json
      - name: Commit Updated price.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add price.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update latest gold price"
            git push
          fi
